#!/usr/bin/env bash

# Exit immediately if the script fails
set -e

clone_path="${clone_path:-"${PWD}"}"
echo "Current working directory: $clone_path"

# Get newest version of nvim
sudo add-apt-repository ppa:neovim-ppa/unstable
apt_packages="curl git python3-pip tmux git neovim zsh fzf fd-find bat direnv keychain"

# Install packages
sudo apt-get update && sudo apt-get install -y ${apt_packages}

# Create initial directories
mkdir -p "${HOME}/.config/zsh"  \
    "${HOME}/.local/bin" "${HOME}/.local/share" \
    "${HOME}/.local/state" "${HOME}/.cache/zsh" 

# Setup local git
cp "${clone_path}/.gitconfig.local" "${HOME}/.gitconfig.local"

# Make Bat avaiable in path
ln -fs /usr/bin/batcat $HOME/.local/bin/bat

# Install zsh plugins
"${clone_path}/.local/bin/update-zsh-plugins"

# Create symbolic links
rm -rf ~/.config/nvim;
ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv" \
    && ln -fs "${clone_path}/.config/zsh/.zshrc" "${HOME}/.config/zsh/.zshrc" \
    && ln -fs "${clone_path}/.config/zsh/.zprofile" "${HOME}/.config/zsh/.zprofile" \
    && ln -fs "${clone_path}/.config/zsh/.aliases" "${HOME}/.config/zsh/.aliases" \
    && ln -fs "${clone_path}/.gitconfig" "${HOME}/.gitconfig" \
    && ln -fs "${clone_path}/.vimrc" "${HOME}/.vimrc" \
    && ln -fs "${clone_path}/.vimrc.minimal" "${HOME}/.vimrc.minimal" \
    && ln -fs "${clone_path}/.config/nvim" "${HOME}/.config/nvim" \
    && ln -fs "${clone_path}/.local/bin/update-zsh-plugins" "${HOME}/.local/bin/update-zsh-plugins" \
	&& ln -fs "${clone_path}/.starship/starfield.toml" "${HOME}/.config/starfield.toml" \

if grep -qE "(Microsoft|microsoft|WSL)" /proc/version &>/dev/null; then
    sudo ln -fs "${clone_path}/etc/wsl.conf" /etc/wsl.conf
fi

# Install Starship
curl -sS https://starship.rs/install.sh | sh

# Change default shell to zsh
chsh -s $(which zsh) $USER

cat << EOF
Everything was installed successfully!
EOF

exit 0
